import Header from "@/components/Page/Web/Header/Header";
import Background from "@/assets/img/background.jpg";
import { Metadata } from "next";
import Image from "next/image";
import React from "react";
import Footer from "@/components/Page/Web/Footer/Footer";

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }: Props) => {
  return (
    <>
      <Header />
      <Image
        src={Background}
        className="w-full object-cover -z-10 fixed top-0"
        alt=""
      />
      <div className="mt-[110px] flex justify-center">
        <div className="w-[1400px] bg-white flex flex-col justify-between">
          {children}
          <Footer />
        </div>
      </div>
    </>
  );
};

export default layout;
