import Header from "@/components/Web/Header";
import Background from "@/assets/img/background.jpg";
import { Metadata } from "next";
import Image from "next/image";
import React from "react";
import Footer from "@/components/Web/Footer";

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }: Props) => {
  return (
    <>
      <Header />
      <Image
        src={Background}
        className="w-full object-cover -z-10 fixed top-0"
        alt=""
      />
      <div className="px-80 pt-40">
        <div className="h-[1000px] bg-white flex flex-col justify-between">
          {children}
          <Footer />
        </div>
      </div>
    </>
  );
};

export default layout;
